---
- hosts: all
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes

  - name: Remove package apache2
    apt:
      name: apache2
      state: absent

  - name: add php for apache
    apt:
      name: libapache2-mod-php
      state: absent
  