---
- hosts: all
  become: true
  pre_tasks:

  - name: Update repo for Fedora
    tags: always
    dnf:
      state: latest
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Update repo for Ubuntu
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
  
- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
